UPDATE articles
SET body = body || char(10) || char(10) ||
  CASE category
    WHEN 'Market access' THEN 'Decision frame: define the exact product configuration, destination, importer role and planned launch date before choosing a route. A market-access conclusion should identify which rules apply, who owns each obligation and what evidence must exist before the first commercial shipment.'
    WHEN 'Labeling' THEN 'Decision frame: treat label content as controlled compliance data rather than final-stage artwork. Confirm the regulated product name, composition or technical attributes, responsible business, origin statement, warnings, language and placement rules before design approval.'
    WHEN 'Regulatory update' THEN 'Decision frame: separate the legal change from the operational change. Record the affected territory, products, transition dates, accepted alternatives and the point at which purchasing, testing, documentation or artwork must change.'
    WHEN 'Documentation' THEN 'Decision frame: a compliance file must prove that the marketed product matches the evidence. Define document owners, model and material identifiers, version control, retention periods and the link between declarations, reports, specifications and production lots.'
    WHEN 'Waste compliance' THEN 'Decision frame: producer-responsibility duties depend on the product category, sales model and party first placing goods on the market. Confirm registration, scheme membership, reporting, financing and marking duties before sales begin.'
    WHEN 'Product safety' THEN 'Decision frame: start with foreseeable users, use conditions and hazards, then map each risk to a design control, warning, test or traceability measure. The safety conclusion should cover the final product, packaging, accessories and online offer.'
    WHEN 'Chemical compliance' THEN 'Decision frame: chemical compliance is specific to materials, substances, suppliers and intended use. Build a bill of materials, identify high-risk components, select the current restriction list and define when declarations are sufficient or testing is needed.'
    WHEN 'Testing' THEN 'Decision frame: the test plan must represent the marketed article and foreseeable use. Define samples, standards, conditioning, food or user contact conditions, pass criteria and the relationship between the tested construction and production goods.'
    WHEN 'Manufacturing' THEN 'Decision frame: manufacturing controls turn a one-time assessment into ongoing conformity. Define approved inputs, process parameters, release checks, change control, nonconformance handling and records that connect each finished lot to its materials.'
    WHEN 'Certification' THEN 'Decision frame: classify the product and authorization route before commissioning a laboratory or certification body. Confirm the responsible applicant, accepted standards, representative sample, required statements and post-approval change rules.'
    WHEN 'Customs' THEN 'Decision frame: customs readiness combines product classification, origin, value, admissibility and document consistency. Align the commercial description, invoice, packing list, markings and regulatory evidence before the shipment reaches the border.'
    ELSE 'Decision frame: define the product, destination, responsible party, applicable rule and evidence threshold before making a launch decision. Record assumptions and assign an owner to every unresolved point.'
  END || char(10) || char(10) ||
  CASE market_id
    WHEN 'eu' THEN 'EU scope: identify the manufacturer, importer and any authorised representative, then distinguish Union-wide legislation from member-state registration, language and enforcement requirements. Keep the Declaration of Conformity and technical evidence aligned with the exact model and economic-operator information shown to customers.'
    WHEN 'us' THEN 'US scope: review the federal agency rule first, then screen state requirements and the importer obligations that arise at entry. Product descriptions, certificates, test reports, labels and supplier records should use consistent model and material identifiers so an agency question can be answered quickly.'
    WHEN 'uk' THEN 'UK scope: separate Great Britain from Northern Ireland where the conformity route differs. Confirm the current acceptance policy, responsible UK business, marking and declaration route, and retain evidence that matches the product version placed on the relevant market.'
    ELSE 'Market scope: verify both national rules and any local registration, language or enforcement layer. Keep the responsible economic operator and destination-specific evidence explicit in the launch record.'
  END || char(10) || char(10) ||
  CASE product_id
    WHEN 'electronics' THEN 'Evidence pack: maintain the product specification, circuit and critical-component information, risk assessment, applicable standards list, laboratory reports, supplier declarations, user instructions, label artwork and change history. Radio, energy, chemical, waste and general safety duties may require separate owners even when they share one technical file.'
    WHEN 'textiles' THEN 'Evidence pack: retain fibre and material specifications, supplier composition data, country-of-origin basis, care-instruction support, restricted-substance evidence, flammability or children-product testing where relevant, label approvals and production-lot traceability. Accessories, coatings, prints and packaging should be included in the risk review.'
    WHEN 'food-contact' THEN 'Evidence pack: identify every material layer and substance, supplier and lawful basis, intended food types, contact time and temperature, repeat-use conditions, migration or composition testing, declarations, GMP controls and lot traceability. Marketing claims must not exceed the conditions supported by the assessment.'
    ELSE 'Evidence pack: connect specifications, supplier evidence, test results, declarations, labels and production records to the exact article offered for sale. Material or supplier changes should trigger a documented reassessment.'
  END || char(10) || char(10) ||
  'Execution sequence: assign a regulatory owner, freeze the assessed product specification, verify the official source, create a gap list, commission only the necessary evidence, review customer-facing information and approve the launch record. For "' || title || '", record the decision date, source version, reviewer and next review trigger so the conclusion remains usable after a supplier or rule change.' || char(10) || char(10) ||
  CASE category
    WHEN 'Labeling' THEN 'Common failure modes include designing from unverified supplier data, omitting a destination language, using a claim broader than the evidence, and updating packaging without updating the compliance file. Release artwork only after the underlying specification and responsible-party data are approved.'
    WHEN 'Documentation' THEN 'Common failure modes include generic declarations, mismatched model numbers, expired reports, missing supplier versions and files that cannot be tied to a production lot. A short document index with owners and review dates is often more useful than an unstructured folder.'
    WHEN 'Testing' THEN 'Common failure modes include testing a nonrepresentative sample, using the wrong use condition, overlooking accessories or variants and accepting a report without checking scope and pass criteria. Record why the selected method covers the final marketed product.'
    WHEN 'Chemical compliance' THEN 'Common failure modes include declarations without material identity, testing only the main substrate, using an outdated restricted-substance list and failing to reassess after a supplier change. Focus verification effort on the components and exposure scenarios with the highest credible risk.'
    WHEN 'Product safety' THEN 'Common failure modes include reviewing only normal use, treating warnings as a substitute for design controls, overlooking vulnerable users and lacking an incident or recall workflow. Close significant risks before launch and preserve the reasoning behind residual-risk decisions.'
    ELSE 'Common failure modes include relying on an undated web page, applying a rule to the wrong product variant, leaving the importer or producer role undefined and collecting evidence after shipment. Use the official reference below as the starting point and obtain specialist advice for ambiguous classifications.'
  END,
  updated_at = '2026-08-15'
WHERE status = 'published' AND length(body) < 500;
