INSERT OR IGNORE INTO markets (id, name, region, summary) VALUES
  ('us', 'United States', 'North America', 'Federal requirements, labeling, testing and market-entry signals for US imports.'),
  ('eu', 'European Union', 'Europe', 'EU-wide market access requirements, harmonised rules and responsible-person obligations.'),
  ('uk', 'United Kingdom', 'Europe', 'UK product safety, labeling and conformity requirements after Brexit.');

INSERT OR IGNORE INTO products (id, name, slug, summary) VALUES
  ('electronics', 'Electronic Products', 'electronics', 'Consumer and industrial electronic products, chargers and connected devices.'),
  ('textiles', 'Textiles & Apparel', 'textiles', 'Garments, footwear, home textiles and fiber-content labeling.'),
  ('food-contact', 'Food Contact Materials', 'food-contact', 'Packaging, containers and materials intended to contact food.');

INSERT OR IGNORE INTO requirements (market_id, product_id, type, title, summary, mandatory, legal_basis, official_url, effective_from, last_verified_at) VALUES
  ('eu', 'electronics', 'certification', 'CE marking', 'Most products covered by EU harmonised legislation need conformity assessment and CE marking before being placed on the market.', 1, 'EU product harmonisation framework', 'https://single-market-economy.ec.europa.eu/single-market/ce-marking_en', '2024-01-01', '2026-08-15'),
  ('eu', 'electronics', 'restriction', 'RoHS substance restrictions', 'Electrical and electronic equipment must comply with restrictions on certain hazardous substances and retain technical documentation.', 1, 'Directive 2011/65/EU', 'https://environment.ec.europa.eu/topics/waste-and-recycling/rohs-directive_en', '2024-01-01', '2026-08-15'),
  ('eu', 'electronics', 'documentation', 'EU Declaration of Conformity', 'The manufacturer or authorised representative must prepare and keep the applicable declaration of conformity.', 1, 'EU conformity assessment framework', 'https://single-market-economy.ec.europa.eu/single-market/ce-marking_en', '2024-01-01', '2026-08-15'),
  ('us', 'electronics', 'certification', 'FCC equipment authorisation', 'Radio-frequency devices may require FCC equipment authorisation before marketing in the United States.', 1, '47 CFR Parts 2 and 15', 'https://www.fcc.gov/engineering-technology/laboratory-division/general/equipment-authorization', '2024-01-01', '2026-08-15'),
  ('us', 'textiles', 'labeling', 'Fiber content and care labeling', 'Most textile products must show fiber content, country of origin and responsible company information.', 1, 'Textile Fiber Products Identification Act', 'https://www.ecfr.gov/current/title-16/chapter-I/subchapter-C/part-303', '2024-01-01', '2026-08-15'),
  ('uk', 'electronics', 'certification', 'UKCA or accepted CE route', 'Products placed on the Great Britain market must follow the applicable UK conformity route and marking rules.', 1, 'UK product safety framework', 'https://www.gov.uk/guidance/using-the-ukca-marking', '2024-01-01', '2026-08-15'),
  ('eu', 'textiles', 'labeling', 'Textile fibre labelling', 'Textile products must use prescribed fibre names and provide composition information in the languages required by the destination market.', 1, 'Regulation (EU) No 1007/2011', 'https://eur-lex.europa.eu/eli/reg/2011/1007/oj/eng', '2024-01-01', '2026-08-15'),
  ('eu', 'food-contact', 'safety', 'Food contact safety framework', 'Materials intended to contact food must not transfer constituents in quantities that endanger health or alter food composition.', 1, 'Regulation (EC) No 1935/2004', 'https://food.ec.europa.eu/food-safety/chemical-safety/food-contact-materials_en', '2024-01-01', '2026-08-15');

INSERT OR IGNORE INTO articles (slug, title, excerpt, body, category, market_id, product_id, published_at, updated_at, source_url) VALUES
  ('eu-electronics-market-entry', 'EU market entry for electronic products', 'A practical first pass through CE marking, RoHS evidence and the documents an importer should request.', 'Start by identifying the applicable harmonised legislation and the role of the manufacturer, importer and authorised representative. Build a technical file before placing the product on the market, then retain the Declaration of Conformity and supporting test evidence.', 'Market access', 'eu', 'electronics', '2026-08-15', '2026-08-15', 'https://single-market-economy.ec.europa.eu/single-market/ce-marking_en'),
  ('us-textile-labeling-basics', 'US textile labeling basics for exporters', 'Fiber content, origin and responsible-company information are the three checks that catch many first-time exporters.', 'The label should identify the generic fiber names in descending percentage order, show the country of origin and provide the required company identity. Treat this as a product and packaging workflow, not a final design check.', 'Labeling', 'us', 'textiles', '2026-08-14', '2026-08-14', 'https://www.ecfr.gov/current/title-16/chapter-I/subchapter-C/part-303'),
  ('ukca-ce-route', 'UKCA and the accepted CE route', 'The right conformity route depends on the product legislation, destination market and current transition rules.', 'Separate Great Britain from Northern Ireland in your launch checklist. Confirm the applicable UK legislation, whether self-declaration is allowed and whether an approved body is required.', 'Regulatory update', 'uk', 'electronics', '2026-08-12', '2026-08-12', 'https://www.gov.uk/guidance/using-the-ukca-marking');

INSERT OR IGNORE INTO providers (slug, name, provider_type, markets, specialties, website, description, verification_status, last_verified_at) VALUES
  ('ul-solutions', 'UL Solutions', 'Testing laboratory', 'US,EU,UK', 'Electronics,product safety,market access', 'https://www.ul.com/', 'Testing, inspection and certification services for product safety and market access.', 'editorial', '2026-08-15'),
  ('intertek', 'Intertek', 'Testing laboratory', 'US,EU,UK', 'Electronics,textiles,food contact', 'https://www.intertek.com/', 'Assurance, testing, inspection and certification services across consumer and industrial products.', 'editorial', '2026-08-15'),
  ('sgs', 'SGS', 'Testing laboratory', 'US,EU,UK', 'Electronics,textiles,food contact', 'https://www.sgs.com/', 'Global testing, inspection and certification services with broad product coverage.', 'editorial', '2026-08-15'),
  ('tuv-rheinland', 'TUV Rheinland', 'Certification body', 'US,EU,UK', 'Electronics,product safety,CE', 'https://www.tuv.com/', 'Independent testing, inspection and certification services for international market access.', 'editorial', '2026-08-15'),
  ('bureau-veritas', 'Bureau Veritas', 'Testing laboratory', 'US,EU,UK', 'Consumer products,textiles,food contact', 'https://group.bureauveritas.com/', 'Testing, inspection and certification services for quality, health, safety and sustainability.', 'editorial', '2026-08-15');
